
spring.application.name=Movie_Booking

server.port=8080

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=MovieDB;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

tmdb.api.key=937207e0287a3ebc5406681bff05c07e